/* jconfigint.h.  Generated by configure.  */
/* libjpeg-turbo build number */
#define BUILD "20141016"

/* How to obtain function inlining. */
#define INLINE inline __attribute__((always_inline))

/* Define to the full name of this package. */
#define PACKAGE_NAME "libjpeg-turbo"

/* Version number of package */
#define VERSION "1.3.90"
